name: morphling
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Dependency Injection
  get_it: ^7.2.0
  
  #Lint
  intl: ^0.19.0

  #Shimmer
  shimmer: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/manto.jpg
